
# ### Variables 
# @url = http://localhost:3003


# #

### Post 

POST http://localhost:3003/user/signup 
Content-Type: application/json

{
    "name":"BernardoBraga",
    "email":"bernar.sbraga@yahoo.com",
    "password":"palmeiras"
}

###

